---
title: "ptarmigan_trends_analysis"
author: "Diana Bowler"
date: "2 november 2017"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

Look at trends in the group size

```{r}

ggplot(subset(allData,!is.na(totalIndiv)),aes(x=Year,y=totalIndiv,group=LinjeID))+
  geom_point(aes(colour=LinjeID))+
  geom_line(aes(colour=LinjeID))+
  facet_wrap(~Fylkesnavn)+
  theme(legend.position="none")

```

How many groups do we usually have per line per year?

```{r}

nuGroups<-ddply(allDetections,.(LinjeID,Year),summarise,nuGroups=length(LinjeAvstand))
summary(nuGroups$nuGroups)

```


Run model in JAGS 

```{r}

source('script/bugsFunctions.R')

setwd("models")

params <- c("int.gs","line.sd","site.sd","year.sd","line.year.sd","site.year.sd",
            "expGroupSize","predGroupSize","random.gs.line.year",
            "randomJT")

out1 <- jags(bugs.data, inits=NULL, params, "group_size_model.txt", n.thin=nt,
               n.chains=3, n.burnin=200,n.iter=1000)

```

Print output

```{r results='asis'}

#library(ggmcmc)
#ggs_traceplot(ggs(out1$samples)) 

print(out1,2)
#save(out1,file="out1_group_size_model_basic.RData")
save(out1,file="out1_group_size_model.RData")

```

#compare with observed group size

```{r results='asis'}

allDetections$expGroupSize <- out1$mean$expGroupSize
allDetectionsSummary<-ddply(allDetections,.(Year,LinjeID,Fylkesnavn),summarise,
                            totalIndiv=mean(totalIndiv),
                            expGroupSize=mean(expGroupSize))

qplot(expGroupSize,totalIndiv,data=allDetectionsSummary)+facet_wrap(~Fylkesnavn)


```

Check that expected and predicted values are the same

```{r, results='asis'}

predictedDF<-data.frame(out1$summary[grepl("predGroupSize",row.names(out1$summary)),])
predictedDF$ParamNu <- as.character(gsub(".*\\[([^][]+)].*", "\\1", row.names(predictedDF)))
predictedDF$matchingLine<-sapply(predictedDF$ParamNu,function(x)strsplit(x,",")[[1]][1])
predictedDF$Year<-as.numeric(sapply(predictedDF$ParamNu,function(x)strsplit(x,",")[[1]][2]))+2006


#add to all detections file
allDetections$preds<-predictedDF$mean[match(interaction(allDetections$Year,allDetections$LinjeID),
                                            interaction(predictedDF$Year,predictedDF$matchingLine))]

qplot(preds,expGroupSize,data=allDetections)

```

```{r}

lineYears<-data.frame(index=bugs.data$detectionLineYear)
lineYears$re<-out1$mean$random.gs.line.year[bugs.data$detectionLineYear]
allDetections$re<-lineYears$re

#line/year combinations
allCombos<-expand.grid(Site=unique(allDetections$Rapporteringsniva),Year=unique(allDetections$Year)-2006)

#index all data points by transect and year for use in the model
TransYrIdx<-matrix(nrow=nrow(allDetections),ncol=nrow(allCombos))
TransYrIdx[]<-0
for(i in 1:nrow(allDetections)){
  TransYrIdx[i,which(allCombos$Year==(allDetections$Year[i]-2006)&
    allCombos$Site==allDetections$Rapporteringsniva[i])]<-1
}

#add to bugs data
bugs.data$allCombos<-as.matrix(allCombos)
bugs.data$n.allCombos<-nrow(allCombos)
bugs.data$TransYrIdx<-TransYrIdx

```