---
title: "combined_model_covariates"
author: "Diana Bowler"
date: "14 november 2017"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

#Get Rodent data

```{r results='asis'}
library(ggplot2)
allData$SettSmagnager<-as.numeric(allData$SettSmagnager)

#get averag per fylke
rodentData <- ddply(allData,.(Year,Fylkesnavn),summarise,
                    rodents = mean(SettSmagnager,na.rm=T))

#plotting
qplot(Year,rodents,data=rodentData,geom=c("point","line"))+
          theme(legend.position = "none")+
          facet_wrap(~Fylkesnavn)

#by rapport...
rodentData <- ddply(allData,.(Year,Fylkesnavn,Rapporteringsniva),summarise,
                    rodents = mean(SettSmagnager,na.rm=T),
                    totalIndiv=mean(totalIndiv,na.rm=T))

library(boot)
rodentData$rodents[is.na(rodentData$rodents)]<-0
rodentData$rodents<- inv.logit(rodentData$rodents)

#plotting
qplot(Year,rodents,data=rodentData,geom=c("point","line"),
      colour=Rapporteringsniva)+
          theme(legend.position = "none")+
          facet_wrap(~Fylkesnavn)

#subset(out,Rapporteringsniva=="Indre Troms")
#   Fylkesnavn Rapporteringsniva
#17   Nordland       Indre Troms
#39      Troms       Indre Troms
```


#Organise the covariate

```{r}

#choose my covariate
myCovariate =rodentData
myCovariate<-subset(myCovariate,Year%in%nuIndivs$Year)
myCovariate$site<-paste(myCovariate$Fylkesnavn,myCovariate$Rapporteringsniva,sep="_")
covariateMatrix = my.n
rowNames<-as.character(sapply(row.names(my.n),function(x)strsplit(as.character(x),"#")[[1]][1]))

all(myCovariate$Rapporteringsniva%in%rowNames)
all(myCovariate$Year%in%dimnames(covariateMatrix)[[2]])

#do we have a value for every combinations
table(myCovariate$Year)

for(i in 1:nrow(covariateMatrix)){
  for(j in 1:ncol(covariateMatrix)){
    covariateMatrix[i,j] = myCovariate$rodents[myCovariate$site==rowNames[i]&
                                              myCovariate$Year==dimnames(covariateMatrix)[[2]][j]]
  }
}


#split into spatial and temporal anomalies
spatialMatrix<-as.numeric(rowMeans(covariateMatrix))
temporalMatrix<-as.numeric(colMeans(covariateMatrix))

#look at summaries
summary(spatialMatrix)
summary(temporalMatrix)

#make a DF
temporalDF<-data.frame(Year=dimnames(my.n)[[2]],value=temporalMatrix)
spatialDF<-data.frame(LinjeID=rowNames,value=spatialMatrix)

##make anomalies
bugs.data$temporalMatrix <- apply(covariateMatrix,2,function(x)x-spatialMatrix)
bugs.data$spatialMatrix <- t(apply(covariateMatrix,1,function(x)x-temporalMatrix))
bugs.data$spatialMatrix2 <- bugs.data$spatialMatrix^2#also add a polynomial term for the spatial variation

#temporal
tMmelted<-melt(bugs.data$temporalMatrix)
allData$Covariate<-tMmelted$value[match(interaction(allData$Year,allData$Line),
                                           interaction(tMmelted$Var2,tMmelted$Var1))]

ggplot(allData,aes(x=Covariate,y=totalIndiv,group=LinjeID))+
  geom_point(aes(colour=factor(Fylkesnavn)))+
  geom_line(aes(colour=factor(Fylkesnavn)))+
  theme(legend.position="none")+
  ggtitle("temporal")

#spatial
tMmelted<-melt(bugs.data$spatialMatrix)
allData$Covariate<-tMmelted$value[match(interaction(allData$Year,allData$Line),
                                           interaction(tMmelted$Var2,tMmelted$Var1))]

ggplot(allData,aes(x=Covariate,y=totalIndiv,group=LinjeID))+
  geom_point(aes(colour=factor(Fylkesnavn)))+
  geom_line(aes(colour=factor(Fylkesnavn)))+
  theme(legend.position="none")+
  ggtitle("spatial")

```

#Alternative plotting

```{r results='asis'}
tMmelted<-melt(bugs.data$temporalMatrix)
allData$Covariate<-tMmelted$value[match(interaction(allData$Year,allData$Line),
                                           interaction(tMmelted$Var2,tMmelted$Var1))]

ggplot(allData,aes(x=Covariate,y=totalIndiv,group=LinjeID))+
  geom_point(aes(colour=factor(OmradeID)))+
  theme(legend.position="none")+
  ggtitle("temporal")+
  facet_wrap(~Fylkesnavn,scales="free")


tMmelted<-melt(bugs.data$spatialMatrix)
allData$Covariate<-tMmelted$value[match(interaction(allData$Year,allData$Line),
                                           interaction(tMmelted$Var2,tMmelted$Var1))]

ggplot(allData,aes(x=Covariate,y=totalIndiv,group=LinjeID))+
  geom_point(aes(colour=factor(OmradeID)))+
  theme(legend.position="none")+
  ggtitle("spatial")+
  facet_wrap(~Fylkesnavn)

```


Spatial pattern and temporal anomalies

```{r}

#the temporal anomalies are the same
#the spatial pattern is now assumed to be fixed
bugs.data$spatialMatrix <- cbind(spatialMatrix,spatialMatrix,spatialMatrix,spatialMatrix,spatialMatrix,spatialMatrix,spatialMatrix,spatialMatrix,spatialMatrix,spatialMatrix)
bugs.data$spatialMatrix2 <-bugs.data$spatialMatrix^2
bugs.data$spatialMatrix<-bugs.data$spatialMatrix-median(bugs.data$spatialMatrix)
bugs.data$spatialMatrix2<-bugs.data$spatialMatrix2-median(bugs.data$spatialMatrix2)

```


#Fit a basic model against abundance

```{r}

params <- c("int.d","beta.covariateS","beta.covariateT","pred.Time","pred.Space")

out1 <- jags(bugs.data, inits=NULL, params, "combined_model_covariateTS.txt", n.thin=nt,
               n.chains=3, n.burnin=400,n.iter=5000,parallel = T)

```

#Print the output

```{r}
print(out1,2)
save(out1,file="out1_rodent.RData")

```

#Fit a model with ar1 term
```{r}

#year one priors
bugs.data$year1<-as.numeric(apply(my.n,1,function(x)ifelse(!is.na(x[1]),x[1],max(x,na.rm=T))))
bugs.data$year1[bugs.data$year1==0]<-1

params <- c("int.d","beta.auto","beta.covariateS","beta.covariateT","pred.Time","pred.Space")

out1 <- jags(bugs.data, inits=NULL, params, "combined_model_covariateTS_ar1.txt", n.thin=nt,
               n.chains=3, n.burnin=2000,n.iter=10000,parallel = T)

```

#Print the output

```{r}
print(out1,2)
save(out1,file="out1_rodent.RData")

```

#modelling the probability see a rodent

```{r warning=FALSE}

my.rodents <- acast(allData,Line~Year,value.var="SettSmagnager",fun=max,na.rm=T)
my.rodents[is.infinite(my.rodents)]<-NA
bugs.data$rodentData <- my.rodents

#model the variation with random effects
source('/data/home/diana.bowler/NorskPtarmigan/script/bugsFunctions.R')

params <- c("int.r","line.r.sd","year.r.sd","site2.r.sd","year.site2.r.sd",
            "spatialRodents","temporalRodents")

#inits <- function(){list(int.r)}

setwd("/data/home/diana.bowler/NorskPtarmigan/models")
out1 <- jags(bugs.data, inits=NULL, params, "rodent_model.txt", n.thin=nt,
               n.chains=3, n.burnin=1000,n.iter=5000,parallel = T)

```
#Print the output

```{r}
print(out1,2)
setwd("/data/home/diana.bowler/NorskPtarmigan/model_outputs")
save(out1,file="out1_rodent_model_only.RData")

```

#Compare the random effects with the % data

```{r}

#compare spatial effects
randomDF <- data.frame(rodentProb=out1$mean$spatialRodents)
randomDF <- cbind(randomDF,siteInfo)
randomDF$matchingSite <- sapply(randomDF$Line,function(x)strsplit(as.character(x),"#")[[1]][1])
randomDF <- merge(randomDF,spatialDF,by.x="matchingSite",by.y="LinjeID")

qplot(rodentProb,value,data=randomDF)+ggtitle("spatial")#correlates pretty well!!
      
qplot(rodentProb,value,data=randomDF,colour=Rapporteringsniva)+
  facet_wrap(~Fylkesnavn)+ggtitle("spatial")+
  theme(legend.position="none")

#compare temporal effects
randomDF<-data.frame(out1$summary[grepl("temporalRodents",row.names(out1$summary)),])
randomDF$Param<-sub(".*\\[([^][]+)].*", "\\1", row.names(randomDF))
randomDF$matchingSite<-as.numeric(sapply(randomDF$Param,function(x)strsplit(x,",")[[1]][1]))
randomDF <- merge(randomDF,siteInfo,by.x="matchingSite",by.y="LinjeID")
randomDF$Year<-as.numeric(sapply(randomDF$Param,function(x)strsplit(x,",")[[1]][2]))+2006
tMmelted<-melt(bugs.data$temporalMatrix)
randomDF<-merge(randomDF,tMmelted,by.x=c("Line","Year"),by.y=c(names(tMmelted)[1:2]))

qplot(mean,value,data=randomDF)+ggtitle("temporal")#correlates pretty well!!
      
qplot(mean,value,data=randomDF,colour=Rapporteringsniva)+
  facet_wrap(~Fylkesnavn)+ggtitle("temporal")+
  theme(legend.position="none")
#correlates really well!!

```


```{r}

source('/data/home/diana.bowler/NorskPtarmigan/script/bugsFunctions.R')

#year one priors
bugs.data$year1<-as.numeric(apply(my.n,1,function(x)ifelse(!is.na(x[1]),x[1],max(x,na.rm=T))))
bugs.data$year1[bugs.data$year1==0]<-1

params <- c("int.d","beta.auto","beta.covariateS","beta.covariateT")

setwd("/data/home/diana.bowler/NorskPtarmigan/models")
out1 <- jags(bugs.data, inits=NULL, params, "combined_model_covariateTS_ar1_rodents.txt", n.thin=nt,n.chains=3, n.burnin=5000,n.iter=20000,parallel = T)

```

Get results

```{r}
print(out1,2)
setwd("/data/home/diana.bowler/NorskPtarmigan/model_outputs")
save(out1,file="out1_rodent2.RData")

```