---
title: "combined_model_springOnset"
author: "Diana Bowler"
date: "14 november 2017"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

#get the data on spring

```{r results='asis'}
setwd("/data/home/diana.bowler/climaticFiles")

load("springData.RData")
springData<-ddply(springData,.(OmradeID,Year),summarise,value=median(value,na.rm=T))
head(springData)

#plotting
qplot(Year,value,data=springData,geom=c("point","line"),colour=OmradeID)+
  theme(legend.position = "none")

```

#Organise the data

```{r}

myCovariate = springData
myCovariate = subset(myCovariate,OmradeID%in%nuIndivs$OmradeID & Year%in%nuIndivs$Year)
covariateMatrix = my.n
rowNames<-as.character(sapply(row.names(my.n),function(x)strsplit(as.character(x),"#")[[1]][2]))
rowNames<-as.character(sapply(rowNames,function(x)strsplit(as.character(x),"-")[[1]][1]))

for(i in 1:nrow(covariateMatrix)){
  for(j in 1:ncol(covariateMatrix)){
    covariateMatrix[i,j] = myCovariate$value[myCovariate$OmradeID==rowNames[i]&
                                              myCovariate$Year==dimnames(covariateMatrix)[[2]][j]]
  }
}

#split into spatial and temporal anomalies
spatialMatrix<-as.numeric(rowMeans(covariateMatrix))
temporalMatrix<-as.numeric(colMeans(covariateMatrix))

#make a DF
temporalDF<-data.frame(Year=dimnames(my.n)[[2]],value=temporalMatrix)
spatialDF<-data.frame(OmradeID=rowNames,value=spatialMatrix)

#look at summaries
summary(spatialMatrix)
summary(temporalMatrix)

#make anomalies
bugs.data$temporalMatrix <- apply(covariateMatrix,2,function(x)x-spatialMatrix)
bugs.data$spatialMatrix <- t(apply(covariateMatrix,1,function(x)x-temporalMatrix))
bugs.data$spatialMatrix2 <- bugs.data$spatialMatrix^2#also add a polynomial term for the spatial variation

#plot the data

#temporal
tMmelted<-melt(bugs.data$temporalMatrix)
allData$Covariate<-tMmelted$value[match(interaction(allData$Year,allData$Line),
                                           interaction(tMmelted$X2,tMmelted$X1))]

ggplot(allData,aes(x=Covariate,y=totalIndiv,group=LinjeID))+
  geom_point(aes(colour=factor(Fylkesnavn)))+
  geom_line(aes(colour=factor(Fylkesnavn)))+
  theme(legend.position="none")+
  ggtitle("temporal")

#spatial
tMmelted<-melt(bugs.data$spatialMatrix)
allData$Covariate<-tMmelted$value[match(interaction(allData$Year,allData$Line),
                                           interaction(tMmelted$X2,tMmelted$X1))]

ggplot(allData,aes(x=Covariate,y=totalIndiv,group=LinjeID))+
  geom_point(aes(colour=factor(Fylkesnavn)))+
  geom_line(aes(colour=factor(Fylkesnavn)))+
  theme(legend.position="none")+
  ggtitle("spatial")

```

#Spatial pattern and temporal anomalies

the temporal anomalies are the same as above

the spatial pattern is now assumed to be fixed across years

```{r}

bugs.data$spatialMatrix <-spatialMatrix
bugs.data$spatialMatrix2 <-bugs.data$spatialMatrix^2
bugs.data$spatialMatrix<-bugs.data$spatialMatrix-median(bugs.data$spatialMatrix)
bugs.data$spatialMatrix2<-bugs.data$spatialMatrix2-median(bugs.data$spatialMatrix2)

sd(bugs.data$temporalMatrix)
sd(bugs.data$spatialMatrix)
```

Fit glm

```{r}

source('/data/home/diana.bowler/NorskPtarmigan/script/bugsFunctions.R')

params <- c("int.d","obs.d.sd","line.d.sd","site.d.sd",
            "b.df.0","b.group.size",
            "beta.covariateS","beta.covariateT","predESW")

setwd("/data/home/diana.bowler/NorskPtarmigan/models")
out1 <- jags(bugs.data, inits=NULL, params, "combined_model_covariateTS_glm.txt", n.thin=nt,
               n.chains=3, n.burnin=1000,n.iter=5000,parallel = T)

```

Print output
```{r}
print(out1,2)
setwd("/data/home/diana.bowler/NorskPtarmigan/model_outputs")
save(out1,file="out1_springOnset_glm.RData")

``` 
Fit glm scaled

```{r}
bugs.data$spatialMatrix<-scale(bugs.data$spatialMatrix)

bugs.data$temporalMatrix<-scale(bugs.data$temporalMatrix)

source('/data/home/diana.bowler/NorskPtarmigan/script/bugsFunctions.R')

params <- c("int.d","obs.d.sd","line.d.sd","site.d.sd",
            "b.df.0","b.group.size",
            "beta.covariateS","beta.covariateT")

setwd("/data/home/diana.bowler/NorskPtarmigan/models")
out1 <- jags(bugs.data, inits=NULL, params, "combined_model_covariateTS_glm.txt", n.thin=nt,
               n.chains=3, n.burnin=500,n.iter=2000,parallel = T)
print(out1,2)
setwd("/data/home/diana.bowler/NorskPtarmigan/model_outputs")
save(out1,file="out1_springOnset_glm_scaled.RData")
```

#Fit a basic model against abundance

```{r}

source('/data/home/diana.bowler/NorskPtarmigan/script/bugsFunctions.R')

params <- c("int.d","obs.d.sd","line.d.sd","b.df.0","b.group.size",
            "beta.covariateS","beta.covariateT","predESW")

setwd("/data/home/diana.bowler/NorskPtarmigan/models")
out1 <- jags(bugs.data, inits=NULL, params, "combined_model_covariateTS.txt", n.thin=nt,
               n.chains=3, n.burnin=2000,n.iter=10000,parallel = T)

```

Print the output

```{r}
print(out1,2)
setwd("/data/home/diana.bowler/NorskPtarmigan/model_outputs")
save(out1,file="out1_springOnset_basic.RData")

```

#plotting the results

```{r}

#effect of space
library(reshape2)
dataspatialMelt<-melt(out1$mean$pred.Space)
dataspatialMelt2<-melt(out1$q2.5$pred.Space)
dataspatialMelt3<-melt(out1$q97.5$pred.Space)
spatialMatrixMelt<-melt(bugs.data$spatialMatrix)
dataspatialMelt$springOnset<-spatialMatrixMelt$value
dataspatialMelt$lower<-dataspatialMelt2$value
dataspatialMelt$upper<-dataspatialMelt3$value

ggplot(dataspatialMelt)+geom_point(aes(x=springOnset,y=value))+geom_ribbon(aes(x=springOnset,ymin=lower,ymax=upper),alpha=0.5)+
  theme_classic()+ggtitle("Spatial variation")

#effect of time
library(reshape2)
dataspatialMelt<-melt(out1$mean$pred.Time)
dataspatialMelt2<-melt(out1$q2.5$pred.Time)
dataspatialMelt3<-melt(out1$q97.5$pred.Time)
spatialMatrixMelt<-melt(bugs.data$temporalMatrix)
dataspatialMelt$springOnset<-spatialMatrixMelt$value
dataspatialMelt$lower<-dataspatialMelt2$value
dataspatialMelt$upper<-dataspatialMelt3$value

ggplot(dataspatialMelt)+geom_point(aes(x=springOnset,y=value))+geom_ribbon(aes(x=springOnset,ymin=lower,ymax=upper),alpha=0.5)+
  theme_classic()+ggtitle("Temporal variation")


```

#Fit a model with ar1 term

```{r}

#year one priors
bugs.data$year1<-as.numeric(apply(my.n,1,function(x)ifelse(!is.na(x[1]),x[1],max(x,na.rm=T))))
bugs.data$year1[bugs.data$year1==0]<-1

params <- c("int.d","beta.auto","beta.covariateS","beta.covariateT","pred.Time","pred.Space")

out1 <- jags(bugs.data, inits=NULL, params, "combined_model_covariateTS_ar1.txt", n.thin=nt,
               n.chains=3, n.burnin=400,n.iter=5000,parallel = T)

```

Print the output

```{r}
print(out1,2)

save(out1,file="out1_springOnset.RData")

```

#plotting the results

```{r}

#effect of space
library(reshape2)
dataspatialMelt<-melt(out1$mean$pred.Space)
dataspatialMelt2<-melt(out1$q2.5$pred.Space)
dataspatialMelt3<-melt(out1$q97.5$pred.Space)
spatialMatrixMelt<-melt(bugs.data$spatialMatrix)
dataspatialMelt$springOnset<-spatialMatrixMelt$value
dataspatialMelt$lower<-dataspatialMelt2$value
dataspatialMelt$upper<-dataspatialMelt3$value

ggplot(dataspatialMelt)+geom_point(aes(x=springOnset,y=value))+geom_ribbon(aes(x=springOnset,ymin=lower,ymax=upper),alpha=0.5)+
  theme_classic()+ggtitle("Spatial variation")

#effect of time
library(reshape2)
dataspatialMelt<-melt(out1$mean$pred.Time)
dataspatialMelt2<-melt(out1$q2.5$pred.Time)
dataspatialMelt3<-melt(out1$q97.5$pred.Time)
spatialMatrixMelt<-melt(bugs.data$temporalMatrix)
dataspatialMelt$springOnset<-spatialMatrixMelt$value
dataspatialMelt$lower<-dataspatialMelt2$value
dataspatialMelt$upper<-dataspatialMelt3$value

ggplot(dataspatialMelt)+geom_point(aes(x=springOnset,y=value))+geom_ribbon(aes(x=springOnset,ymin=lower,ymax=upper),alpha=0.5)+
  theme_classic()+ggtitle("Temporal variation")


```

