---
title: "ptarmigan_trends_analysis"
author: "Diana Bowler"
date: "2 november 2017"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

Fit the model without the trend term and just random year to year variation, that also varies by fylk and rapp

Run model in JAGS

```{r}
source('/data/home/diana.bowler/NorskPtarmigan/script/bugsFunctions.R')

params <- c("int.d","line.d.sd","year.d.sd","site.d.sd","site2.d.sd","syear.d.sd","s2year.d.sd",
            "b.df.0","b.group.size",
            "int.gs","line.sd","line.year.sd","Density","predGroupSize")

setwd("/data/home/diana.bowler/NorskPtarmigan/models")
out1 <- jags(bugs.data, inits=NULL, params, "combined_model_noTrend.txt", n.thin=nt,
               n.chains=3, n.burnin=3000,n.iter=7000,parallel = T)
```

Save and print the model

```{r results='asis'}

print(out1,2)
setwd("/data/home/diana.bowler/NorskPtarmigan/model_outputs")
#save(out1,file="out1_ptarmigan_noTrends.RData")#group size model is random line and year
save(out1,file="out1_ptarmigan_noTrends2.RData")#group size model is random line and line/year
```

get and check group size predictions

```{r}
out<-getBUGSFits(out1,param="predGroupSize")

#get mean group size for detections
meanGP<-ddply(allDetections,.(LinjeID,Year),summarise,meanGP=mean(totalIndiv))
out$meanGP<-meanGP$meanGP[match(interaction(out$lineIndex,out$Year),interaction(meanGP$LinjeID,meanGP$Year))]
qplot(mean,meanGP,data=out)
#ok!
```

Pull out and plot the density estimates:

```{r results='asis'}
#Have they converged
setwd("/data/home/diana.bowler/NorskPtarmigan/model_outputs")
load("out1_ptarmigan_noTrends.RData")
densityDF<-data.frame(meanNu=out1$mean$Density)
densityDF$LinjeID<-1:nrow(densityDF)
densityDF<-merge(densityDF,siteInfo,by="LinjeID")
temp<-sapply(densityDF$Line,function(x)strsplit(as.character(x),"-")[[1]][1])
densityDF$Fylkesnavn<-sapply(temp,function(x)strsplit(x,"_")[[1]][1])
densityDF$Rapporteringsniva<-sapply(temp,function(x)strsplit(x,"_")[[1]][2])
densityDF$originalLinjeID<-sapply(densityDF$Line,function(x)strsplit(as.character(x),"-")[[1]][2])
densityDF<-melt(densityDF,id=c("LinjeID","Line","Fylkesnavn","Rapporteringsniva","originalLinjeID"))
densityDF$variable<-gsub("meanNu.","",densityDF$variable)
densityDF$Year<-as.numeric(as.character(densityDF$variable))+2006
densityDF$value<-as.numeric(as.character(densityDF$value))

qplot(Year,value,data=densityDF,group=LinjeID,colour=Rapporteringsniva,geom="path",facets=~Fylkesnavn)+
  theme_light()+
  theme(legend.position="none")+ylab("Predicted Density km2")
#each site seems to have its own dynamic over time as specified by the model

```

Look at spatial pattern:

```{r}
#get average abundance per linjeID
linePredictions <- ddply(densityDF,.(originalLinjeID),summarise,density=mean(value))

#get line spatial info
setwd("/data/home/diana.bowler/climaticFiles")
load("Lines_utm.RData")

#add mean densities and remove those without mean density data
Lines_utm$density <- linePredictions$density[match(Lines_utm@data$LinjeID,linePredictions$originalLinjeID)]
Lines_utm <- subset(Lines_utm,!is.na(density))

#plot it
library(sp)
mySLDF_fortify <- fortify(Lines_utm)
mySLDF_fortify$density <- linePredictions$density[match(mySLDF_fortify$id,linePredictions$originalLinjeID)]

ggplot(mySLDF_fortify, aes(x=long, y=lat, group=group,colour=log(density+1))) + 
  geom_path(size=rel(3)) +
  theme_minimal()+
  scale_colour_gradient2(low="red",mid="gray90",high="dodgerblue",midpoint=2.51)+
  xlab("x")+ylab("y")

#get temperature map
setwd("/data/home/diana.bowler/GeoSpatialData/AdministrativeUnits/Norway_AdministrativeUnits/Processed")
counties<-readOGR(getwd(),layer="Norway_ADM_fylke_FLATE")
counties<-spTransform(counties,CRS(proj4string(Lines_utm)))
plot(counties)
counties@data$id <- 1:nrow(counties@data)
counties.fort <- fortify(counties, region='id')
ggplot(counties.fort, aes(x = long, y = lat, group = id)) + 
  geom_polygon(fill="white")+
  geom_path(data=mySLDF_fortify, aes(x=long, y=lat, group=group,colour=log(density+1)),size=rel(3)) +
  scale_colour_gradient2(low="red",mid="gray90",high="dodgerblue",midpoint=2.51)+
  xlab("x")+ylab("y")

```

